class NotFoundError(Exception):
    pass


class AlreadyExistsError(Exception):
    pass
